baseurl = "/"
languageCode = "en-us"
title = "Travis's Notepad"
theme = "minimal"
pluralizelisttitles = false
relativeurls = true

[params]
  author = "Travis Hall"
  description = "Random thoughts and observations"
  githubUsername = "tvs"
  accent = "grey"
  showBorder = true
  backgroundColor = "white"
  font = "Raleway"
  highlight = true
  highlightStyle = "railscasts"
  highlightLanguages = ["go", "ruby", "yaml", "erb", "bash"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/cfcr/"
    name = "CFCR"
    weight = 2

[[menu.main]]
    url = "/notes/"
    name = "Notes"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:trvs.hll@gmail.com  "
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/tvs/"
    name = "github"
    weight = 2

#[[menu.icon]]
#    url = "https://twitter.com/username/"
#    name = "twitter"
#    weight = 3
#
#[[menu.icon]]
#    url = "https://www.linkedin.com/in/username/"
#    name = "linkedin"
#    weight = 4
#
#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "stack-overflow"
#    weight = 5
